### ISSUE TITLE
Question on contributing 

### ISSUE THREAD

**Issue by craigcooper11** [einride/backstage-go#18]
Hello @odsod! I see you are the owner of this repo. I was wondering if you are currently accepting PR for new features? I was looking at adding a new field here, https://pkg.go.dev/go.einride.tech/backstage/catalog#EntityRelation that would expose the target. I.E

```{
        "type": "consumesApi",
        "targetRef": "component:default/artist-lookup",
        "target": {
          "kind": "component",
          "namespace": "default",
          "name": "artist-lookup"
        }
      }
 ```

**Comment by odsod** [comment]
@craigcooper11 Sounds good to me, please fire away a PR and let's have a look at it!

**Comment by odsod** [comment]
@craigcooper11 Just a quick question - the relation schema doesn't seem to have a `target` key - if what you're looking for is a parsed version of the entity ref, how about using a separate parser? As much as possible, let's try and stick to the schema!
